### ISSUE TITLE
Resolve 500 errors for some addresses

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#19]
It seems that some addresses are returning a 500 error. Example below:

### Request

```
{
    "addressFull": "125 Estates Cir, Lake Mary, FL 32746-3044"
}
``` 

### Response

```
{
    "errors": [
        {
            "message": "{:code :radiantlabs.http-client.core/http-request-error, :status 400, :response {:request-time 223, :request {:user-info nil, :http-client #object[jdk.internal.net.http.HttpClientFacade 0x1e0720a1 \"jdk.internal.net.http.HttpClientImpl@4e5558b1(1)\"], :as :json, :headers {\"accept\" \"application/json\", \"apikey\" \"6d97bf52961a5a1922af42d086f565c1\", \"accept-encoding\" \"gzip, deflate\"}, :server-port nil, :url \"https://api.gateway.attomdata.com/propertyapi/v1.0.0/property/buildingpermits\", :throw-exceptions false, :coerce :always, :http-request #object[jdk.internal.net.http.HttpRequestImpl 0x2e5311ea \"https://api.gateway.attomdata.com/propertyapi/v1.0.0/property/buildingpermits?address1=125+Estates+Cir&address2=Lake+Mary%2C+FL+32746-3044 GET\"], :uri \"/propertyapi/v1.0.0/property/buildingpermits\", :server-name \"api.gateway.attomdata.com\", :query-string \"address1=125+Estates+Cir&address2=Lake+Mary%2C+FL+32746-3044\", :scheme :https, :request-method :get}, :http-client #object[jdk.internal.net.http.HttpClientFacade 0x1e0720a1 \"jdk.internal.net.http.HttpClientImpl@4e5558b1(1)\"], :headers {\":status\" \"400\", \"content-type\" \"application/json; charset=utf-8\", \"date\" \"Wed, 20 Sep 2023 12:14:09 GMT\", \"request-context\" \"appId=cid-v1:7dd6a845-9f7f-4079-af3a-cb0496df36e3\", \"strict-transport-security\" \"max-age=2592000\", \"x-azure-ref\" \"20230920T121409Z-tzmyd5dwm5245d44m9wcr17fcg00000001b000000001q4hn\", \"x-cache\" \"CONFIG_NOCACHE\"}, :status 400, :content-type :application/json, :uri \"https://api.gateway.attomdata.com/propertyapi/v1.0.0/property/buildingpermits?address1=125+Estates+Cir&address2=Lake+Mary%2C+FL+32746-3044\", :content-type-params {:charset \"utf-8\"}, :version :http-2, :body {:status {:version \"1.0.0\", :code 1, :msg \"SuccessWithoutResult\", :total 1, :page 1, :pagesize 10, :transactionID \"f4be1bea3d97f590c135c313479ccbd4\"}, :property []}}}",
            "code": "timelines-handler-error"
        }
    ]
}
```

**Comment by jefffriesen** [comment]
These were terrible errors. We fixed and deployed that. But we are having issues with Florida addresses that we are currently working on. Here is the new error message:
```
{
"errors": [
{
"message": "Missing value for EGRID_CO2E_EMISSIONS_RATE_LB_PER_MWH",
"code": "missing-egrid-co2-coefficient"
}
]
}
```

**Comment by joshuamzm** [comment]
We've just deployed a fix to resolve Florida addresses correctly. The address `125 Estates Cir, Lake Mary, FL 32746-3044` is now returning a correct answer:

![image](https://github.com/RadiantLabs/modeling-api-docs/assets/10285345/2da1a766-45b1-4455-bf4b-610ec8fba83a)

@lukeduran Let us know if this is working better for you.

**Comment by kloconnell** [comment]
@lukeduran I just retried your original request in this issue and it still appears to be modeling correctly.
